# automatically generated by the FlatBuffers compiler, do not modify

# namespace: CWM

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class AcknowledgeThreatRequest(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = AcknowledgeThreatRequest()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsAcknowledgeThreatRequest(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # AcknowledgeThreatRequest
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # AcknowledgeThreatRequest
    def CommandId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

def AcknowledgeThreatRequestStart(builder):
    builder.StartObject(1)

def Start(builder):
    AcknowledgeThreatRequestStart(builder)

def AcknowledgeThreatRequestAddCommandId(builder, commandId):
    builder.PrependUint64Slot(0, commandId, 0)

def AddCommandId(builder, commandId):
    AcknowledgeThreatRequestAddCommandId(builder, commandId)

def AcknowledgeThreatRequestEnd(builder):
    return builder.EndObject()

def End(builder):
    return AcknowledgeThreatRequestEnd(builder)
