# automatically generated by the FlatBuffers compiler, do not modify

# namespace: CWM

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class AttackRequest(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = AttackRequest()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsAttackRequest(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # AttackRequest
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # AttackRequest
    def CommandId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # AttackRequest
    def TargetEntityId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

def AttackRequestStart(builder):
    builder.StartObject(2)

def Start(builder):
    AttackRequestStart(builder)

def AttackRequestAddCommandId(builder, commandId):
    builder.PrependUint64Slot(0, commandId, 0)

def AddCommandId(builder, commandId):
    AttackRequestAddCommandId(builder, commandId)

def AttackRequestAddTargetEntityId(builder, targetEntityId):
    builder.PrependUint64Slot(1, targetEntityId, 0)

def AddTargetEntityId(builder, targetEntityId):
    AttackRequestAddTargetEntityId(builder, targetEntityId)

def AttackRequestEnd(builder):
    return builder.EndObject()

def End(builder):
    return AttackRequestEnd(builder)
