# automatically generated by the FlatBuffers compiler, do not modify

# namespace: CWM

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ChunkSnapshot(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ChunkSnapshot()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsChunkSnapshot(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ChunkSnapshot
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ChunkSnapshot
    def ChunkX(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ChunkSnapshot
    def ChunkY(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ChunkSnapshot
    def ChunkZ(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ChunkSnapshot
    def SizeX(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # ChunkSnapshot
    def SizeY(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # ChunkSnapshot
    def SizeZ(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # ChunkSnapshot
    def Blocks(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 8
            from CDDA.CWM.CwmBlock import CwmBlock
            obj = CwmBlock()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ChunkSnapshot
    def BlocksLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ChunkSnapshot
    def BlocksIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        return o == 0

def ChunkSnapshotStart(builder):
    builder.StartObject(7)

def Start(builder):
    ChunkSnapshotStart(builder)

def ChunkSnapshotAddChunkX(builder, chunkX):
    builder.PrependInt32Slot(0, chunkX, 0)

def AddChunkX(builder, chunkX):
    ChunkSnapshotAddChunkX(builder, chunkX)

def ChunkSnapshotAddChunkY(builder, chunkY):
    builder.PrependInt32Slot(1, chunkY, 0)

def AddChunkY(builder, chunkY):
    ChunkSnapshotAddChunkY(builder, chunkY)

def ChunkSnapshotAddChunkZ(builder, chunkZ):
    builder.PrependInt32Slot(2, chunkZ, 0)

def AddChunkZ(builder, chunkZ):
    ChunkSnapshotAddChunkZ(builder, chunkZ)

def ChunkSnapshotAddSizeX(builder, sizeX):
    builder.PrependUint8Slot(3, sizeX, 0)

def AddSizeX(builder, sizeX):
    ChunkSnapshotAddSizeX(builder, sizeX)

def ChunkSnapshotAddSizeY(builder, sizeY):
    builder.PrependUint8Slot(4, sizeY, 0)

def AddSizeY(builder, sizeY):
    ChunkSnapshotAddSizeY(builder, sizeY)

def ChunkSnapshotAddSizeZ(builder, sizeZ):
    builder.PrependUint8Slot(5, sizeZ, 0)

def AddSizeZ(builder, sizeZ):
    ChunkSnapshotAddSizeZ(builder, sizeZ)

def ChunkSnapshotAddBlocks(builder, blocks):
    builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(blocks), 0)

def AddBlocks(builder, blocks):
    ChunkSnapshotAddBlocks(builder, blocks)

def ChunkSnapshotStartBlocksVector(builder, numElems):
    return builder.StartVector(8, numElems, 4)

def StartBlocksVector(builder, numElems):
    return ChunkSnapshotStartBlocksVector(builder, numElems)

def ChunkSnapshotEnd(builder):
    return builder.EndObject()

def End(builder):
    return ChunkSnapshotEnd(builder)
