# automatically generated by the FlatBuffers compiler, do not modify

# namespace: CWM

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class CommandAck(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = CommandAck()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsCommandAck(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # CommandAck
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # CommandAck
    def CommandId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # CommandAck
    def Accepted(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # CommandAck
    def ErrorMessage(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # CommandAck
    def ResultRevision(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

def CommandAckStart(builder):
    builder.StartObject(4)

def Start(builder):
    CommandAckStart(builder)

def CommandAckAddCommandId(builder, commandId):
    builder.PrependUint64Slot(0, commandId, 0)

def AddCommandId(builder, commandId):
    CommandAckAddCommandId(builder, commandId)

def CommandAckAddAccepted(builder, accepted):
    builder.PrependBoolSlot(1, accepted, 0)

def AddAccepted(builder, accepted):
    CommandAckAddAccepted(builder, accepted)

def CommandAckAddErrorMessage(builder, errorMessage):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(errorMessage), 0)

def AddErrorMessage(builder, errorMessage):
    CommandAckAddErrorMessage(builder, errorMessage)

def CommandAckAddResultRevision(builder, resultRevision):
    builder.PrependUint64Slot(3, resultRevision, 0)

def AddResultRevision(builder, resultRevision):
    CommandAckAddResultRevision(builder, resultRevision)

def CommandAckEnd(builder):
    return builder.EndObject()

def End(builder):
    return CommandAckEnd(builder)
