# automatically generated by the FlatBuffers compiler, do not modify

# namespace: CWM

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ContinuousIntentRequest(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ContinuousIntentRequest()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsContinuousIntentRequest(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ContinuousIntentRequest
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ContinuousIntentRequest
    def CommandId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # ContinuousIntentRequest
    def X(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # ContinuousIntentRequest
    def Y(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def ContinuousIntentRequestStart(builder):
    builder.StartObject(3)

def Start(builder):
    ContinuousIntentRequestStart(builder)

def ContinuousIntentRequestAddCommandId(builder, commandId):
    builder.PrependUint64Slot(0, commandId, 0)

def AddCommandId(builder, commandId):
    ContinuousIntentRequestAddCommandId(builder, commandId)

def ContinuousIntentRequestAddX(builder, x):
    builder.PrependFloat32Slot(1, x, 0.0)

def AddX(builder, x):
    ContinuousIntentRequestAddX(builder, x)

def ContinuousIntentRequestAddY(builder, y):
    builder.PrependFloat32Slot(2, y, 0.0)

def AddY(builder, y):
    ContinuousIntentRequestAddY(builder, y)

def ContinuousIntentRequestEnd(builder):
    return builder.EndObject()

def End(builder):
    return ContinuousIntentRequestEnd(builder)
