# automatically generated by the FlatBuffers compiler, do not modify

# namespace: CWM

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class CwmBlock(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 8

    # CwmBlock
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # CwmBlock
    def StateFlags(self): return self._tab.Get(flatbuffers.number_types.Uint32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # CwmBlock
    def MaterialId(self): return self._tab.Get(flatbuffers.number_types.Uint16Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(4))
    # CwmBlock
    def LightLevel(self): return self._tab.Get(flatbuffers.number_types.Uint8Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(6))
    # CwmBlock
    def Orientation(self): return self._tab.Get(flatbuffers.number_types.Uint8Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(7))

def CreateCwmBlock(builder, stateFlags, materialId, lightLevel, orientation):
    builder.Prep(4, 8)
    builder.PrependUint8(orientation)
    builder.PrependUint8(lightLevel)
    builder.PrependUint16(materialId)
    builder.PrependUint32(stateFlags)
    return builder.Offset()
