# automatically generated by the FlatBuffers compiler, do not modify

# namespace: CWM

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class CwmMessage(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = CwmMessage()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsCwmMessage(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # CwmMessage
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # CwmMessage
    def SequenceNumber(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # CwmMessage
    def WorldRevision(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # CwmMessage
    def TimestampMs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # CwmMessage
    def PayloadType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # CwmMessage
    def Payload(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            from flatbuffers.table import Table
            obj = Table(bytearray(), 0)
            self._tab.Union(obj, o)
            return obj
        return None

    # CwmMessage
    def SessionId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # CwmMessage
    def PlayerId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # CwmMessage
    def ConnectionId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

def CwmMessageStart(builder):
    builder.StartObject(8)

def Start(builder):
    CwmMessageStart(builder)

def CwmMessageAddSequenceNumber(builder, sequenceNumber):
    builder.PrependUint64Slot(0, sequenceNumber, 0)

def AddSequenceNumber(builder, sequenceNumber):
    CwmMessageAddSequenceNumber(builder, sequenceNumber)

def CwmMessageAddWorldRevision(builder, worldRevision):
    builder.PrependUint64Slot(1, worldRevision, 0)

def AddWorldRevision(builder, worldRevision):
    CwmMessageAddWorldRevision(builder, worldRevision)

def CwmMessageAddTimestampMs(builder, timestampMs):
    builder.PrependUint64Slot(2, timestampMs, 0)

def AddTimestampMs(builder, timestampMs):
    CwmMessageAddTimestampMs(builder, timestampMs)

def CwmMessageAddPayloadType(builder, payloadType):
    builder.PrependUint8Slot(3, payloadType, 0)

def AddPayloadType(builder, payloadType):
    CwmMessageAddPayloadType(builder, payloadType)

def CwmMessageAddPayload(builder, payload):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(payload), 0)

def AddPayload(builder, payload):
    CwmMessageAddPayload(builder, payload)

def CwmMessageAddSessionId(builder, sessionId):
    builder.PrependUint64Slot(5, sessionId, 0)

def AddSessionId(builder, sessionId):
    CwmMessageAddSessionId(builder, sessionId)

def CwmMessageAddPlayerId(builder, playerId):
    builder.PrependUint64Slot(6, playerId, 0)

def AddPlayerId(builder, playerId):
    CwmMessageAddPlayerId(builder, playerId)

def CwmMessageAddConnectionId(builder, connectionId):
    builder.PrependUint64Slot(7, connectionId, 0)

def AddConnectionId(builder, connectionId):
    CwmMessageAddConnectionId(builder, connectionId)

def CwmMessageEnd(builder):
    return builder.EndObject()

def End(builder):
    return CwmMessageEnd(builder)
