# automatically generated by the FlatBuffers compiler, do not modify

# namespace: CWM

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class DecisionResponse(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = DecisionResponse()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsDecisionResponse(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # DecisionResponse
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # DecisionResponse
    def DecisionId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # DecisionResponse
    def Choice(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

def DecisionResponseStart(builder):
    builder.StartObject(2)

def Start(builder):
    DecisionResponseStart(builder)

def DecisionResponseAddDecisionId(builder, decisionId):
    builder.PrependUint64Slot(0, decisionId, 0)

def AddDecisionId(builder, decisionId):
    DecisionResponseAddDecisionId(builder, decisionId)

def DecisionResponseAddChoice(builder, choice):
    builder.PrependUint16Slot(1, choice, 0)

def AddChoice(builder, choice):
    DecisionResponseAddChoice(builder, choice)

def DecisionResponseEnd(builder):
    return builder.EndObject()

def End(builder):
    return DecisionResponseEnd(builder)
