# automatically generated by the FlatBuffers compiler, do not modify

# namespace: CWM

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class DecisionPrompt(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = DecisionPrompt()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsDecisionPrompt(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # DecisionPrompt
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # DecisionPrompt
    def DecisionId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # DecisionPrompt
    def Text(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # DecisionPrompt
    def Choices(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.String(a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return ""

    # DecisionPrompt
    def ChoicesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # DecisionPrompt
    def ChoicesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

def DecisionPromptStart(builder):
    builder.StartObject(3)

def Start(builder):
    DecisionPromptStart(builder)

def DecisionPromptAddDecisionId(builder, decisionId):
    builder.PrependUint64Slot(0, decisionId, 0)

def AddDecisionId(builder, decisionId):
    DecisionPromptAddDecisionId(builder, decisionId)

def DecisionPromptAddText(builder, text):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(text), 0)

def AddText(builder, text):
    DecisionPromptAddText(builder, text)

def DecisionPromptAddChoices(builder, choices):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(choices), 0)

def AddChoices(builder, choices):
    DecisionPromptAddChoices(builder, choices)

def DecisionPromptStartChoicesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartChoicesVector(builder, numElems):
    return DecisionPromptStartChoicesVector(builder, numElems)

def DecisionPromptEnd(builder):
    return builder.EndObject()

def End(builder):
    return DecisionPromptEnd(builder)
