# automatically generated by the FlatBuffers compiler, do not modify

# namespace: CWM

class EntityType(object):
    PLAYER = 0
    NPC = 1
    MONSTER = 2
    VEHICLE = 3
    ITEM = 4
    FIELD_EFFECT = 5
