# automatically generated by the FlatBuffers compiler, do not modify

# namespace: CWM

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class EntityRemoved(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = EntityRemoved()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsEntityRemoved(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # EntityRemoved
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # EntityRemoved
    def Id(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

def EntityRemovedStart(builder):
    builder.StartObject(1)

def Start(builder):
    EntityRemovedStart(builder)

def EntityRemovedAddId(builder, id):
    builder.PrependUint64Slot(0, id, 0)

def AddId(builder, id):
    EntityRemovedAddId(builder, id)

def EntityRemovedEnd(builder):
    return builder.EndObject()

def End(builder):
    return EntityRemovedEnd(builder)
