# automatically generated by the FlatBuffers compiler, do not modify

# namespace: CWM

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class EntitySpawned(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = EntitySpawned()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsEntitySpawned(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # EntitySpawned
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # EntitySpawned
    def State(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from CDDA.CWM.EntityState import EntityState
            obj = EntityState()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def EntitySpawnedStart(builder):
    builder.StartObject(1)

def Start(builder):
    EntitySpawnedStart(builder)

def EntitySpawnedAddState(builder, state):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(state), 0)

def AddState(builder, state):
    EntitySpawnedAddState(builder, state)

def EntitySpawnedEnd(builder):
    return builder.EndObject()

def End(builder):
    return EntitySpawnedEnd(builder)
