# automatically generated by the FlatBuffers compiler, do not modify

# namespace: CWM

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class EntityState(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = EntityState()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsEntityState(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # EntityState
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # EntityState
    def Id(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # EntityState
    def Type(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # EntityState
    def TypeId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # EntityState
    def Pos(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = o + self._tab.Pos
            from CDDA.CWM.Vec3f import Vec3f
            obj = Vec3f()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # EntityState
    def Rotation(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # EntityState
    def AnimationHint(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

    # EntityState
    def HpPercent(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # EntityState
    def Name(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def EntityStateStart(builder):
    builder.StartObject(8)

def Start(builder):
    EntityStateStart(builder)

def EntityStateAddId(builder, id):
    builder.PrependUint64Slot(0, id, 0)

def AddId(builder, id):
    EntityStateAddId(builder, id)

def EntityStateAddType(builder, type):
    builder.PrependInt8Slot(1, type, 0)

def AddType(builder, type):
    EntityStateAddType(builder, type)

def EntityStateAddTypeId(builder, typeId):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(typeId), 0)

def AddTypeId(builder, typeId):
    EntityStateAddTypeId(builder, typeId)

def EntityStateAddPos(builder, pos):
    builder.PrependStructSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(pos), 0)

def AddPos(builder, pos):
    EntityStateAddPos(builder, pos)

def EntityStateAddRotation(builder, rotation):
    builder.PrependFloat32Slot(4, rotation, 0.0)

def AddRotation(builder, rotation):
    EntityStateAddRotation(builder, rotation)

def EntityStateAddAnimationHint(builder, animationHint):
    builder.PrependUint16Slot(5, animationHint, 0)

def AddAnimationHint(builder, animationHint):
    EntityStateAddAnimationHint(builder, animationHint)

def EntityStateAddHpPercent(builder, hpPercent):
    builder.PrependUint8Slot(6, hpPercent, 0)

def AddHpPercent(builder, hpPercent):
    EntityStateAddHpPercent(builder, hpPercent)

def EntityStateAddName(builder, name):
    builder.PrependUOffsetTRelativeSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)

def AddName(builder, name):
    EntityStateAddName(builder, name)

def EntityStateEnd(builder):
    return builder.EndObject()

def End(builder):
    return EntityStateEnd(builder)
