# automatically generated by the FlatBuffers compiler, do not modify

# namespace: CWM

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class FieldState(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = FieldState()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsFieldState(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # FieldState
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # FieldState
    def Coord(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = o + self._tab.Pos
            from CDDA.CWM.Coord3i import Coord3i
            obj = Coord3i()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # FieldState
    def FieldTypeId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

    # FieldState
    def Density(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # FieldState
    def Age(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def FieldStateStart(builder):
    builder.StartObject(4)

def Start(builder):
    FieldStateStart(builder)

def FieldStateAddCoord(builder, coord):
    builder.PrependStructSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(coord), 0)

def AddCoord(builder, coord):
    FieldStateAddCoord(builder, coord)

def FieldStateAddFieldTypeId(builder, fieldTypeId):
    builder.PrependUint16Slot(1, fieldTypeId, 0)

def AddFieldTypeId(builder, fieldTypeId):
    FieldStateAddFieldTypeId(builder, fieldTypeId)

def FieldStateAddDensity(builder, density):
    builder.PrependUint8Slot(2, density, 0)

def AddDensity(builder, density):
    FieldStateAddDensity(builder, density)

def FieldStateAddAge(builder, age):
    builder.PrependUint32Slot(3, age, 0)

def AddAge(builder, age):
    FieldStateAddAge(builder, age)

def FieldStateEnd(builder):
    return builder.EndObject()

def End(builder):
    return FieldStateEnd(builder)
