# automatically generated by the FlatBuffers compiler, do not modify

# namespace: CWM

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class GroundItemState(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = GroundItemState()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsGroundItemState(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # GroundItemState
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # GroundItemState
    def StackIndex(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # GroundItemState
    def TypeId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # GroundItemState
    def Name(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # GroundItemState
    def Charges(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # GroundItemState
    def CountByCharges(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def GroundItemStateStart(builder):
    builder.StartObject(5)

def Start(builder):
    GroundItemStateStart(builder)

def GroundItemStateAddStackIndex(builder, stackIndex):
    builder.PrependUint32Slot(0, stackIndex, 0)

def AddStackIndex(builder, stackIndex):
    GroundItemStateAddStackIndex(builder, stackIndex)

def GroundItemStateAddTypeId(builder, typeId):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(typeId), 0)

def AddTypeId(builder, typeId):
    GroundItemStateAddTypeId(builder, typeId)

def GroundItemStateAddName(builder, name):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)

def AddName(builder, name):
    GroundItemStateAddName(builder, name)

def GroundItemStateAddCharges(builder, charges):
    builder.PrependInt32Slot(3, charges, 0)

def AddCharges(builder, charges):
    GroundItemStateAddCharges(builder, charges)

def GroundItemStateAddCountByCharges(builder, countByCharges):
    builder.PrependBoolSlot(4, countByCharges, 0)

def AddCountByCharges(builder, countByCharges):
    GroundItemStateAddCountByCharges(builder, countByCharges)

def GroundItemStateEnd(builder):
    return builder.EndObject()

def End(builder):
    return GroundItemStateEnd(builder)
