# automatically generated by the FlatBuffers compiler, do not modify

# namespace: CWM

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class GroundItemTileState(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = GroundItemTileState()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsGroundItemTileState(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # GroundItemTileState
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # GroundItemTileState
    def Coord(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = o + self._tab.Pos
            from CDDA.CWM.Coord3i import Coord3i
            obj = Coord3i()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # GroundItemTileState
    def Items(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from CDDA.CWM.GroundItemState import GroundItemState
            obj = GroundItemState()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # GroundItemTileState
    def ItemsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # GroundItemTileState
    def ItemsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

def GroundItemTileStateStart(builder):
    builder.StartObject(2)

def Start(builder):
    GroundItemTileStateStart(builder)

def GroundItemTileStateAddCoord(builder, coord):
    builder.PrependStructSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(coord), 0)

def AddCoord(builder, coord):
    GroundItemTileStateAddCoord(builder, coord)

def GroundItemTileStateAddItems(builder, items):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(items), 0)

def AddItems(builder, items):
    GroundItemTileStateAddItems(builder, items)

def GroundItemTileStateStartItemsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartItemsVector(builder, numElems):
    return GroundItemTileStateStartItemsVector(builder, numElems)

def GroundItemTileStateEnd(builder):
    return builder.EndObject()

def End(builder):
    return GroundItemTileStateEnd(builder)
