# automatically generated by the FlatBuffers compiler, do not modify

# namespace: CWM

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class HeartbeatAck(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = HeartbeatAck()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsHeartbeatAck(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # HeartbeatAck
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # HeartbeatAck
    def TimestampMs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # HeartbeatAck
    def ServerTimeMs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

def HeartbeatAckStart(builder):
    builder.StartObject(2)

def Start(builder):
    HeartbeatAckStart(builder)

def HeartbeatAckAddTimestampMs(builder, timestampMs):
    builder.PrependUint64Slot(0, timestampMs, 0)

def AddTimestampMs(builder, timestampMs):
    HeartbeatAckAddTimestampMs(builder, timestampMs)

def HeartbeatAckAddServerTimeMs(builder, serverTimeMs):
    builder.PrependUint64Slot(1, serverTimeMs, 0)

def AddServerTimeMs(builder, serverTimeMs):
    HeartbeatAckAddServerTimeMs(builder, serverTimeMs)

def HeartbeatAckEnd(builder):
    return builder.EndObject()

def End(builder):
    return HeartbeatAckEnd(builder)
