# automatically generated by the FlatBuffers compiler, do not modify

# namespace: CWM

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class HelloResponse(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = HelloResponse()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsHelloResponse(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # HelloResponse
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # HelloResponse
    def ProtocolVersionMajor(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

    # HelloResponse
    def ProtocolVersionMinor(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

    # HelloResponse
    def ServerBuildId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # HelloResponse
    def Accepted(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # HelloResponse
    def RejectReason(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # HelloResponse
    def NextCommandId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

def HelloResponseStart(builder):
    builder.StartObject(6)

def Start(builder):
    HelloResponseStart(builder)

def HelloResponseAddProtocolVersionMajor(builder, protocolVersionMajor):
    builder.PrependUint16Slot(0, protocolVersionMajor, 0)

def AddProtocolVersionMajor(builder, protocolVersionMajor):
    HelloResponseAddProtocolVersionMajor(builder, protocolVersionMajor)

def HelloResponseAddProtocolVersionMinor(builder, protocolVersionMinor):
    builder.PrependUint16Slot(1, protocolVersionMinor, 0)

def AddProtocolVersionMinor(builder, protocolVersionMinor):
    HelloResponseAddProtocolVersionMinor(builder, protocolVersionMinor)

def HelloResponseAddServerBuildId(builder, serverBuildId):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(serverBuildId), 0)

def AddServerBuildId(builder, serverBuildId):
    HelloResponseAddServerBuildId(builder, serverBuildId)

def HelloResponseAddAccepted(builder, accepted):
    builder.PrependBoolSlot(3, accepted, 0)

def AddAccepted(builder, accepted):
    HelloResponseAddAccepted(builder, accepted)

def HelloResponseAddRejectReason(builder, rejectReason):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(rejectReason), 0)

def AddRejectReason(builder, rejectReason):
    HelloResponseAddRejectReason(builder, rejectReason)

def HelloResponseAddNextCommandId(builder, nextCommandId):
    builder.PrependUint64Slot(5, nextCommandId, 0)

def AddNextCommandId(builder, nextCommandId):
    HelloResponseAddNextCommandId(builder, nextCommandId)

def HelloResponseEnd(builder):
    return builder.EndObject()

def End(builder):
    return HelloResponseEnd(builder)
