# automatically generated by the FlatBuffers compiler, do not modify

# namespace: CWM

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class HelloRequest(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = HelloRequest()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsHelloRequest(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # HelloRequest
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # HelloRequest
    def ProtocolVersionMajor(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

    # HelloRequest
    def ProtocolVersionMinor(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

    # HelloRequest
    def BuildId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def HelloRequestStart(builder):
    builder.StartObject(3)

def Start(builder):
    HelloRequestStart(builder)

def HelloRequestAddProtocolVersionMajor(builder, protocolVersionMajor):
    builder.PrependUint16Slot(0, protocolVersionMajor, 0)

def AddProtocolVersionMajor(builder, protocolVersionMajor):
    HelloRequestAddProtocolVersionMajor(builder, protocolVersionMajor)

def HelloRequestAddProtocolVersionMinor(builder, protocolVersionMinor):
    builder.PrependUint16Slot(1, protocolVersionMinor, 0)

def AddProtocolVersionMinor(builder, protocolVersionMinor):
    HelloRequestAddProtocolVersionMinor(builder, protocolVersionMinor)

def HelloRequestAddBuildId(builder, buildId):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(buildId), 0)

def AddBuildId(builder, buildId):
    HelloRequestAddBuildId(builder, buildId)

def HelloRequestEnd(builder):
    return builder.EndObject()

def End(builder):
    return HelloRequestEnd(builder)
