# automatically generated by the FlatBuffers compiler, do not modify

# namespace: CWM

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class InteractRequest(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = InteractRequest()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsInteractRequest(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # InteractRequest
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # InteractRequest
    def CommandId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # InteractRequest
    def TargetCoord(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = o + self._tab.Pos
            from CDDA.CWM.Coord3i import Coord3i
            obj = Coord3i()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # InteractRequest
    def Action(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

def InteractRequestStart(builder):
    builder.StartObject(3)

def Start(builder):
    InteractRequestStart(builder)

def InteractRequestAddCommandId(builder, commandId):
    builder.PrependUint64Slot(0, commandId, 0)

def AddCommandId(builder, commandId):
    InteractRequestAddCommandId(builder, commandId)

def InteractRequestAddTargetCoord(builder, targetCoord):
    builder.PrependStructSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(targetCoord), 0)

def AddTargetCoord(builder, targetCoord):
    InteractRequestAddTargetCoord(builder, targetCoord)

def InteractRequestAddAction(builder, action):
    builder.PrependInt8Slot(2, action, 0)

def AddAction(builder, action):
    InteractRequestAddAction(builder, action)

def InteractRequestEnd(builder):
    return builder.EndObject()

def End(builder):
    return InteractRequestEnd(builder)
