# automatically generated by the FlatBuffers compiler, do not modify

# namespace: CWM

class InteractAction(object):
    EXAMINE = 0
    OPEN = 1
    CLOSE = 2
    PICKUP = 3
    DROP = 4
    ATTACK = 5
    SMASH = 6
    USE = 7
