# automatically generated by the FlatBuffers compiler, do not modify

# namespace: CWM

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class MoveRequest(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = MoveRequest()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsMoveRequest(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # MoveRequest
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # MoveRequest
    def CommandId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # MoveRequest
    def Direction(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

def MoveRequestStart(builder):
    builder.StartObject(2)

def Start(builder):
    MoveRequestStart(builder)

def MoveRequestAddCommandId(builder, commandId):
    builder.PrependUint64Slot(0, commandId, 0)

def AddCommandId(builder, commandId):
    MoveRequestAddCommandId(builder, commandId)

def MoveRequestAddDirection(builder, direction):
    builder.PrependInt8Slot(1, direction, 0)

def AddDirection(builder, direction):
    MoveRequestAddDirection(builder, direction)

def MoveRequestEnd(builder):
    return builder.EndObject()

def End(builder):
    return MoveRequestEnd(builder)
