# automatically generated by the FlatBuffers compiler, do not modify

# namespace: CWM

class Payload(object):
    NONE = 0
    HelloRequest = 1
    HelloResponse = 2
    Heartbeat = 3
    HeartbeatAck = 4
    WorldSnapshot = 5
    ChunkSnapshot = 6
    TileDelta = 7
    EntityState = 8
    EntityRemoved = 9
    VehicleState = 10
    FieldState = 11
    MoveRequest = 12
    InteractRequest = 13
    AttackRequest = 14
    CommandAck = 15
    TimeEvent = 16
    AcknowledgeThreatRequest = 17
    DecisionPrompt = 18
    DecisionResponse = 19
