# automatically generated by the FlatBuffers compiler, do not modify

# namespace: CWM

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class SimulationControlRequest(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SimulationControlRequest()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSimulationControlRequest(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # SimulationControlRequest
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SimulationControlRequest
    def CommandId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # SimulationControlRequest
    def Action(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # SimulationControlRequest
    def TimeScale(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 1.0

def SimulationControlRequestStart(builder):
    builder.StartObject(3)

def Start(builder):
    SimulationControlRequestStart(builder)

def SimulationControlRequestAddCommandId(builder, commandId):
    builder.PrependUint64Slot(0, commandId, 0)

def AddCommandId(builder, commandId):
    SimulationControlRequestAddCommandId(builder, commandId)

def SimulationControlRequestAddAction(builder, action):
    builder.PrependInt8Slot(1, action, 0)

def AddAction(builder, action):
    SimulationControlRequestAddAction(builder, action)

def SimulationControlRequestAddTimeScale(builder, timeScale):
    builder.PrependFloat32Slot(2, timeScale, 1.0)

def AddTimeScale(builder, timeScale):
    SimulationControlRequestAddTimeScale(builder, timeScale)

def SimulationControlRequestEnd(builder):
    return builder.EndObject()

def End(builder):
    return SimulationControlRequestEnd(builder)
