# automatically generated by the FlatBuffers compiler, do not modify

# namespace: CWM

class SimulationControl(object):
    PAUSE = 0
    RESUME = 1
    SET_SPEED = 2
    MENU_OPEN = 3
    MENU_CLOSE = 4
