# automatically generated by the FlatBuffers compiler, do not modify

# namespace: CWM

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class SimulationState(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SimulationState()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSimulationState(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # SimulationState
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SimulationState
    def Realtime(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # SimulationState
    def PauseReasons(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # SimulationState
    def TimeScale(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 1.0

def SimulationStateStart(builder):
    builder.StartObject(3)

def Start(builder):
    SimulationStateStart(builder)

def SimulationStateAddRealtime(builder, realtime):
    builder.PrependBoolSlot(0, realtime, 0)

def AddRealtime(builder, realtime):
    SimulationStateAddRealtime(builder, realtime)

def SimulationStateAddPauseReasons(builder, pauseReasons):
    builder.PrependUint32Slot(1, pauseReasons, 0)

def AddPauseReasons(builder, pauseReasons):
    SimulationStateAddPauseReasons(builder, pauseReasons)

def SimulationStateAddTimeScale(builder, timeScale):
    builder.PrependFloat32Slot(2, timeScale, 1.0)

def AddTimeScale(builder, timeScale):
    SimulationStateAddTimeScale(builder, timeScale)

def SimulationStateEnd(builder):
    return builder.EndObject()

def End(builder):
    return SimulationStateEnd(builder)
