# automatically generated by the FlatBuffers compiler, do not modify

# namespace: CWM

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class SnapshotAck(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SnapshotAck()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSnapshotAck(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # SnapshotAck
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SnapshotAck
    def StateId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

def SnapshotAckStart(builder):
    builder.StartObject(1)

def Start(builder):
    SnapshotAckStart(builder)

def SnapshotAckAddStateId(builder, stateId):
    builder.PrependUint64Slot(0, stateId, 0)

def AddStateId(builder, stateId):
    SnapshotAckAddStateId(builder, stateId)

def SnapshotAckEnd(builder):
    return builder.EndObject()

def End(builder):
    return SnapshotAckEnd(builder)
