# automatically generated by the FlatBuffers compiler, do not modify

# namespace: CWM

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class TileDelta(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = TileDelta()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsTileDelta(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # TileDelta
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # TileDelta
    def Coord(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = o + self._tab.Pos
            from CDDA.CWM.Coord3i import Coord3i
            obj = Coord3i()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # TileDelta
    def Block(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = o + self._tab.Pos
            from CDDA.CWM.CwmBlock import CwmBlock
            obj = CwmBlock()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def TileDeltaStart(builder):
    builder.StartObject(2)

def Start(builder):
    TileDeltaStart(builder)

def TileDeltaAddCoord(builder, coord):
    builder.PrependStructSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(coord), 0)

def AddCoord(builder, coord):
    TileDeltaAddCoord(builder, coord)

def TileDeltaAddBlock(builder, block):
    builder.PrependStructSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(block), 0)

def AddBlock(builder, block):
    TileDeltaAddBlock(builder, block)

def TileDeltaEnd(builder):
    return builder.EndObject()

def End(builder):
    return TileDeltaEnd(builder)
