# automatically generated by the FlatBuffers compiler, do not modify

# namespace: CWM

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class TimeEvent(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = TimeEvent()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsTimeEvent(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # TimeEvent
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # TimeEvent
    def WorldRevision(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # TimeEvent
    def SimulationTime(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # TimeEvent
    def TimeJump(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # TimeEvent
    def SimulationBusy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def TimeEventStart(builder):
    builder.StartObject(4)

def Start(builder):
    TimeEventStart(builder)

def TimeEventAddWorldRevision(builder, worldRevision):
    builder.PrependUint64Slot(0, worldRevision, 0)

def AddWorldRevision(builder, worldRevision):
    TimeEventAddWorldRevision(builder, worldRevision)

def TimeEventAddSimulationTime(builder, simulationTime):
    builder.PrependUint64Slot(1, simulationTime, 0)

def AddSimulationTime(builder, simulationTime):
    TimeEventAddSimulationTime(builder, simulationTime)

def TimeEventAddTimeJump(builder, timeJump):
    builder.PrependBoolSlot(2, timeJump, 0)

def AddTimeJump(builder, timeJump):
    TimeEventAddTimeJump(builder, timeJump)

def TimeEventAddSimulationBusy(builder, simulationBusy):
    builder.PrependBoolSlot(3, simulationBusy, 0)

def AddSimulationBusy(builder, simulationBusy):
    TimeEventAddSimulationBusy(builder, simulationBusy)

def TimeEventEnd(builder):
    return builder.EndObject()

def End(builder):
    return TimeEventEnd(builder)
