# automatically generated by the FlatBuffers compiler, do not modify

# namespace: CWM

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class VehicleComponentState(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = VehicleComponentState()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsVehicleComponentState(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # VehicleComponentState
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # VehicleComponentState
    def PartId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # VehicleComponentState
    def Offset(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = o + self._tab.Pos
            from CDDA.CWM.Vec3f import Vec3f
            obj = Vec3f()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # VehicleComponentState
    def Broken(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # VehicleComponentState
    def Open(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def VehicleComponentStateStart(builder):
    builder.StartObject(4)

def Start(builder):
    VehicleComponentStateStart(builder)

def VehicleComponentStateAddPartId(builder, partId):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(partId), 0)

def AddPartId(builder, partId):
    VehicleComponentStateAddPartId(builder, partId)

def VehicleComponentStateAddOffset(builder, offset):
    builder.PrependStructSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(offset), 0)

def AddOffset(builder, offset):
    VehicleComponentStateAddOffset(builder, offset)

def VehicleComponentStateAddBroken(builder, broken):
    builder.PrependBoolSlot(2, broken, 0)

def AddBroken(builder, broken):
    VehicleComponentStateAddBroken(builder, broken)

def VehicleComponentStateAddOpen(builder, open):
    builder.PrependBoolSlot(3, open, 0)

def AddOpen(builder, open):
    VehicleComponentStateAddOpen(builder, open)

def VehicleComponentStateEnd(builder):
    return builder.EndObject()

def End(builder):
    return VehicleComponentStateEnd(builder)
