# automatically generated by the FlatBuffers compiler, do not modify

# namespace: CWM

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class VehicleState(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = VehicleState()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsVehicleState(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # VehicleState
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # VehicleState
    def Id(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # VehicleState
    def Name(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # VehicleState
    def Pivot(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = o + self._tab.Pos
            from CDDA.CWM.Vec3f import Vec3f
            obj = Vec3f()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # VehicleState
    def Rotation(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # VehicleState
    def Velocity(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            x = o + self._tab.Pos
            from CDDA.CWM.Vec3f import Vec3f
            obj = Vec3f()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # VehicleState
    def Components(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from CDDA.CWM.VehicleComponentState import VehicleComponentState
            obj = VehicleComponentState()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # VehicleState
    def ComponentsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # VehicleState
    def ComponentsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        return o == 0

def VehicleStateStart(builder):
    builder.StartObject(6)

def Start(builder):
    VehicleStateStart(builder)

def VehicleStateAddId(builder, id):
    builder.PrependUint64Slot(0, id, 0)

def AddId(builder, id):
    VehicleStateAddId(builder, id)

def VehicleStateAddName(builder, name):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)

def AddName(builder, name):
    VehicleStateAddName(builder, name)

def VehicleStateAddPivot(builder, pivot):
    builder.PrependStructSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(pivot), 0)

def AddPivot(builder, pivot):
    VehicleStateAddPivot(builder, pivot)

def VehicleStateAddRotation(builder, rotation):
    builder.PrependFloat32Slot(3, rotation, 0.0)

def AddRotation(builder, rotation):
    VehicleStateAddRotation(builder, rotation)

def VehicleStateAddVelocity(builder, velocity):
    builder.PrependStructSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(velocity), 0)

def AddVelocity(builder, velocity):
    VehicleStateAddVelocity(builder, velocity)

def VehicleStateAddComponents(builder, components):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(components), 0)

def AddComponents(builder, components):
    VehicleStateAddComponents(builder, components)

def VehicleStateStartComponentsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartComponentsVector(builder, numElems):
    return VehicleStateStartComponentsVector(builder, numElems)

def VehicleStateEnd(builder):
    return builder.EndObject()

def End(builder):
    return VehicleStateEnd(builder)
