# automatically generated by the FlatBuffers compiler, do not modify

# namespace: CWM

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class WorldSnapshot(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = WorldSnapshot()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsWorldSnapshot(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # WorldSnapshot
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # WorldSnapshot
    def WorldRevision(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # WorldSnapshot
    def Origin(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = o + self._tab.Pos
            from CDDA.CWM.Coord3i import Coord3i
            obj = Coord3i()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # WorldSnapshot
    def SimulationTimeSeconds(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # WorldSnapshot
    def Chunks(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from CDDA.CWM.ChunkSnapshot import ChunkSnapshot
            obj = ChunkSnapshot()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # WorldSnapshot
    def ChunksLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # WorldSnapshot
    def ChunksIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0

    # WorldSnapshot
    def Entities(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from CDDA.CWM.EntityState import EntityState
            obj = EntityState()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # WorldSnapshot
    def EntitiesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # WorldSnapshot
    def EntitiesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        return o == 0

    # WorldSnapshot
    def Vehicles(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from CDDA.CWM.VehicleState import VehicleState
            obj = VehicleState()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # WorldSnapshot
    def VehiclesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # WorldSnapshot
    def VehiclesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        return o == 0

    # WorldSnapshot
    def Fields(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from CDDA.CWM.FieldState import FieldState
            obj = FieldState()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # WorldSnapshot
    def FieldsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # WorldSnapshot
    def FieldsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        return o == 0

    # WorldSnapshot
    def Tiles(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from CDDA.CWM.TileDelta import TileDelta
            obj = TileDelta()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # WorldSnapshot
    def TilesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # WorldSnapshot
    def TilesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        return o == 0

    # WorldSnapshot
    def SafetyStop(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # WorldSnapshot
    def Full(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # WorldSnapshot
    def BaseRevision(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # WorldSnapshot
    def StateId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # WorldSnapshot
    def ResyncId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # WorldSnapshot
    def CompletedCommandId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # WorldSnapshot
    def Spawned(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(32))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from CDDA.CWM.EntitySpawned import EntitySpawned
            obj = EntitySpawned()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # WorldSnapshot
    def SpawnedLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(32))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # WorldSnapshot
    def SpawnedIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(32))
        return o == 0

    # WorldSnapshot
    def Removed(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(34))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from CDDA.CWM.EntityRemoved import EntityRemoved
            obj = EntityRemoved()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # WorldSnapshot
    def RemovedLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(34))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # WorldSnapshot
    def RemovedIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(34))
        return o == 0

    # WorldSnapshot
    def Clock(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(36))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from CDDA.CWM.SimulationState import SimulationState
            obj = SimulationState()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # WorldSnapshot
    def GroundItemTiles(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(38))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from CDDA.CWM.GroundItemTileState import GroundItemTileState
            obj = GroundItemTileState()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # WorldSnapshot
    def GroundItemTilesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(38))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # WorldSnapshot
    def GroundItemTilesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(38))
        return o == 0

def WorldSnapshotStart(builder):
    builder.StartObject(18)

def Start(builder):
    WorldSnapshotStart(builder)

def WorldSnapshotAddWorldRevision(builder, worldRevision):
    builder.PrependUint64Slot(0, worldRevision, 0)

def AddWorldRevision(builder, worldRevision):
    WorldSnapshotAddWorldRevision(builder, worldRevision)

def WorldSnapshotAddOrigin(builder, origin):
    builder.PrependStructSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(origin), 0)

def AddOrigin(builder, origin):
    WorldSnapshotAddOrigin(builder, origin)

def WorldSnapshotAddSimulationTimeSeconds(builder, simulationTimeSeconds):
    builder.PrependUint64Slot(2, simulationTimeSeconds, 0)

def AddSimulationTimeSeconds(builder, simulationTimeSeconds):
    WorldSnapshotAddSimulationTimeSeconds(builder, simulationTimeSeconds)

def WorldSnapshotAddChunks(builder, chunks):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(chunks), 0)

def AddChunks(builder, chunks):
    WorldSnapshotAddChunks(builder, chunks)

def WorldSnapshotStartChunksVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartChunksVector(builder, numElems):
    return WorldSnapshotStartChunksVector(builder, numElems)

def WorldSnapshotAddEntities(builder, entities):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(entities), 0)

def AddEntities(builder, entities):
    WorldSnapshotAddEntities(builder, entities)

def WorldSnapshotStartEntitiesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartEntitiesVector(builder, numElems):
    return WorldSnapshotStartEntitiesVector(builder, numElems)

def WorldSnapshotAddVehicles(builder, vehicles):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(vehicles), 0)

def AddVehicles(builder, vehicles):
    WorldSnapshotAddVehicles(builder, vehicles)

def WorldSnapshotStartVehiclesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartVehiclesVector(builder, numElems):
    return WorldSnapshotStartVehiclesVector(builder, numElems)

def WorldSnapshotAddFields(builder, fields):
    builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(fields), 0)

def AddFields(builder, fields):
    WorldSnapshotAddFields(builder, fields)

def WorldSnapshotStartFieldsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartFieldsVector(builder, numElems):
    return WorldSnapshotStartFieldsVector(builder, numElems)

def WorldSnapshotAddTiles(builder, tiles):
    builder.PrependUOffsetTRelativeSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(tiles), 0)

def AddTiles(builder, tiles):
    WorldSnapshotAddTiles(builder, tiles)

def WorldSnapshotStartTilesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartTilesVector(builder, numElems):
    return WorldSnapshotStartTilesVector(builder, numElems)

def WorldSnapshotAddSafetyStop(builder, safetyStop):
    builder.PrependBoolSlot(8, safetyStop, 0)

def AddSafetyStop(builder, safetyStop):
    WorldSnapshotAddSafetyStop(builder, safetyStop)

def WorldSnapshotAddFull(builder, full):
    builder.PrependBoolSlot(9, full, 0)

def AddFull(builder, full):
    WorldSnapshotAddFull(builder, full)

def WorldSnapshotAddBaseRevision(builder, baseRevision):
    builder.PrependUint64Slot(10, baseRevision, 0)

def AddBaseRevision(builder, baseRevision):
    WorldSnapshotAddBaseRevision(builder, baseRevision)

def WorldSnapshotAddStateId(builder, stateId):
    builder.PrependUint64Slot(11, stateId, 0)

def AddStateId(builder, stateId):
    WorldSnapshotAddStateId(builder, stateId)

def WorldSnapshotAddResyncId(builder, resyncId):
    builder.PrependUint64Slot(12, resyncId, 0)

def AddResyncId(builder, resyncId):
    WorldSnapshotAddResyncId(builder, resyncId)

def WorldSnapshotAddCompletedCommandId(builder, completedCommandId):
    builder.PrependUint64Slot(13, completedCommandId, 0)

def AddCompletedCommandId(builder, completedCommandId):
    WorldSnapshotAddCompletedCommandId(builder, completedCommandId)

def WorldSnapshotAddSpawned(builder, spawned):
    builder.PrependUOffsetTRelativeSlot(14, flatbuffers.number_types.UOffsetTFlags.py_type(spawned), 0)

def AddSpawned(builder, spawned):
    WorldSnapshotAddSpawned(builder, spawned)

def WorldSnapshotStartSpawnedVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartSpawnedVector(builder, numElems):
    return WorldSnapshotStartSpawnedVector(builder, numElems)

def WorldSnapshotAddRemoved(builder, removed):
    builder.PrependUOffsetTRelativeSlot(15, flatbuffers.number_types.UOffsetTFlags.py_type(removed), 0)

def AddRemoved(builder, removed):
    WorldSnapshotAddRemoved(builder, removed)

def WorldSnapshotStartRemovedVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartRemovedVector(builder, numElems):
    return WorldSnapshotStartRemovedVector(builder, numElems)

def WorldSnapshotAddClock(builder, clock):
    builder.PrependUOffsetTRelativeSlot(16, flatbuffers.number_types.UOffsetTFlags.py_type(clock), 0)

def AddClock(builder, clock):
    WorldSnapshotAddClock(builder, clock)

def WorldSnapshotAddGroundItemTiles(builder, groundItemTiles):
    builder.PrependUOffsetTRelativeSlot(17, flatbuffers.number_types.UOffsetTFlags.py_type(groundItemTiles), 0)

def AddGroundItemTiles(builder, groundItemTiles):
    WorldSnapshotAddGroundItemTiles(builder, groundItemTiles)

def WorldSnapshotStartGroundItemTilesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartGroundItemTilesVector(builder, numElems):
    return WorldSnapshotStartGroundItemTilesVector(builder, numElems)

def WorldSnapshotEnd(builder):
    return builder.EndObject()

def End(builder):
    return WorldSnapshotEnd(builder)
