# automatically generated by the FlatBuffers compiler, do not modify

# namespace: CWM

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class WorldSnapshot(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = WorldSnapshot()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsWorldSnapshot(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # WorldSnapshot
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # WorldSnapshot
    def WorldRevision(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # WorldSnapshot
    def Origin(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = o + self._tab.Pos
            from CDDA.CWM.Coord3i import Coord3i
            obj = Coord3i()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # WorldSnapshot
    def SimulationTimeSeconds(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # WorldSnapshot
    def Chunks(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from CDDA.CWM.ChunkSnapshot import ChunkSnapshot
            obj = ChunkSnapshot()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # WorldSnapshot
    def ChunksLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # WorldSnapshot
    def ChunksIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0

    # WorldSnapshot
    def Entities(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from CDDA.CWM.EntityState import EntityState
            obj = EntityState()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # WorldSnapshot
    def EntitiesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # WorldSnapshot
    def EntitiesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        return o == 0

    # WorldSnapshot
    def Vehicles(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from CDDA.CWM.VehicleState import VehicleState
            obj = VehicleState()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # WorldSnapshot
    def VehiclesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # WorldSnapshot
    def VehiclesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        return o == 0

    # WorldSnapshot
    def Fields(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from CDDA.CWM.FieldState import FieldState
            obj = FieldState()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # WorldSnapshot
    def FieldsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # WorldSnapshot
    def FieldsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        return o == 0

    # WorldSnapshot
    def Tiles(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from CDDA.CWM.TileDelta import TileDelta
            obj = TileDelta()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # WorldSnapshot
    def TilesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # WorldSnapshot
    def TilesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        return o == 0

def WorldSnapshotStart(builder):
    builder.StartObject(8)

def Start(builder):
    WorldSnapshotStart(builder)

def WorldSnapshotAddWorldRevision(builder, worldRevision):
    builder.PrependUint64Slot(0, worldRevision, 0)

def AddWorldRevision(builder, worldRevision):
    WorldSnapshotAddWorldRevision(builder, worldRevision)

def WorldSnapshotAddOrigin(builder, origin):
    builder.PrependStructSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(origin), 0)

def AddOrigin(builder, origin):
    WorldSnapshotAddOrigin(builder, origin)

def WorldSnapshotAddSimulationTimeSeconds(builder, simulationTimeSeconds):
    builder.PrependUint64Slot(2, simulationTimeSeconds, 0)

def AddSimulationTimeSeconds(builder, simulationTimeSeconds):
    WorldSnapshotAddSimulationTimeSeconds(builder, simulationTimeSeconds)

def WorldSnapshotAddChunks(builder, chunks):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(chunks), 0)

def AddChunks(builder, chunks):
    WorldSnapshotAddChunks(builder, chunks)

def WorldSnapshotStartChunksVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartChunksVector(builder, numElems):
    return WorldSnapshotStartChunksVector(builder, numElems)

def WorldSnapshotAddEntities(builder, entities):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(entities), 0)

def AddEntities(builder, entities):
    WorldSnapshotAddEntities(builder, entities)

def WorldSnapshotStartEntitiesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartEntitiesVector(builder, numElems):
    return WorldSnapshotStartEntitiesVector(builder, numElems)

def WorldSnapshotAddVehicles(builder, vehicles):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(vehicles), 0)

def AddVehicles(builder, vehicles):
    WorldSnapshotAddVehicles(builder, vehicles)

def WorldSnapshotStartVehiclesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartVehiclesVector(builder, numElems):
    return WorldSnapshotStartVehiclesVector(builder, numElems)

def WorldSnapshotAddFields(builder, fields):
    builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(fields), 0)

def AddFields(builder, fields):
    WorldSnapshotAddFields(builder, fields)

def WorldSnapshotStartFieldsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartFieldsVector(builder, numElems):
    return WorldSnapshotStartFieldsVector(builder, numElems)

def WorldSnapshotAddTiles(builder, tiles):
    builder.PrependUOffsetTRelativeSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(tiles), 0)

def AddTiles(builder, tiles):
    WorldSnapshotAddTiles(builder, tiles)

def WorldSnapshotStartTilesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartTilesVector(builder, numElems):
    return WorldSnapshotStartTilesVector(builder, numElems)

def WorldSnapshotEnd(builder):
    return builder.EndObject()

def End(builder):
    return WorldSnapshotEnd(builder)
